Dec-POMDP support added (#42)
* added alias-paynt

* add memory

* build state space

* simplify constructQuotientMdp

* add count successors

* change prints

* change discount factor

* fix build state space

* add max_successor_memory_size and fix global memory set

* add buildTransitionMatrixSpurious

* add constructQuotientStateLabeling

* fix prototype row index

* fix row prototype

* add choice labeling

* fix row prototype

row prototype to all states not onlz for prototype

* fix constructing choice labeling

* construct transition matrix

* fix transition matrix and add reward model

* add supporting functions to coloring

* add reset design space

* add nr_agent_actions_at_observation to cpp

* add holes in cpp

* fix row prototype

* fix row prototype again

* unfinished version of buildDesignSpaceSpurious

* add buildDesignSpaceSpurious

* set memory

* error coloring

* number of rows  does not match state count.

RuntimeError: IllegalArgumentException: Can not create deterministic model: Number of rows of transition matrix does not match state count.

* add basic model

* -

* change for cycle in coloring

* mem fixed

* add agent_max_successor_memory_size

* fix creating memory holes

* fixed coloring

* changed discount in dectiger

* delete prints

* removed prints

* coloring run with fixed memory

* add models

* remove discounted conditions

* added decpomdp models

* added experiment

* added experiments

* new split method

* added made_memory_joint_observation()

* added construct_acton_to_memory_joint_observation

* changes in scheduler_selection

* complete acton_to_memory_joint_observation

* prefers inconsistency of the second type

* removed prints

* added state_to_memory_joint_observation and alternative function

* added nr_memory_joint_observations

* added alternativeComputeInconsistentHoleVariance

* score prefer inconsistency of 1 type

* fixed prefer 1st type

* fixed prefer 1st type

* add models

* added possibility to don't use discount transformation

* added direct setting of target states

* fixed direct setting of target states

* added setting of target states from file

* added setting of props from file

* added infinite models

* added models

* changed circle model

* added iterative function

* added new grid

* changes in grids ERROR

* change small bug

* fix numbers in max succ

* Revert "fix numbers in max succ"

This reverts commit e80fe1f315a52ba238a921943af0696b68ca27eb.

* fixed effectivity of coloring

* fix 0 in max_mem_size

* added prints

* added generator of target states

* return FSC but not working

* after experiments

* addeed coments

* changed agent action labels

* fixing grid

* added coments

* added universal labels

* +

* added grid target

* working

* deleted comments

* Added simple iterative strategy for dec-POMDPs; renamed pomdp-memory-size argument to fsc-memory-size

* Preparing dec-POMDP implementation to support flexible memory update; WORK IN PROGRESS

* dec-POMDP WIP

* dec-POMDP implementation WIP

* Finished Dec-POMDP quotient implementation

* Final improvements of the Dec-POMDP code

* updated README

---------

Co-authored-by: vojtavojta <vojtavojta@github.com>
Co-authored-by: Vojtěch Hranička <vojtahranicka@seznam.cz>